### ISSUE TITLE
Impact on exsisting wallet

### ISSUE THREAD

**Issue by JDP-Maker** [aicjofs/zencash-swing-wallet-ui#1]
Really a question and not an issue.
So just to double check, if we have already been running Eleos, zencash-swing-wallet-ui will access/manage the same wallet zend created and Eleos has been accessing? It will not create a new wallet, correct? If we run swing-wallet, any reason we can't switch back to Eleos?
Thanks its great to have options.

**Comment by aicjofs** [comment]
I know your question was already answered in the Slack for Zen, but it's good info for others that may be looking.  It will not effect the wallet to go between the two.  This wallet is just an overlay for the commandline the real magic is happening at a lower level so both wallets can coexist. Just don't run them at the same time as a precaution.
