### ISSUE TITLE
not synchronizing

### ISSUE THREAD

**Issue by capdavid** [aicjofs/zencash-swing-wallet-ui#2]
Hi,

maybe this is my fault, but I installed the windows GUI zen cash wallet and it's not synchronizing? Have I done anything wrong? It says 0 network connections.

Screen: http://imgur.com/a/kM6t6

Also, I am already using Zcash wallet similar to this one.

Thanks,
David

**Comment by aicjofs** [comment]
Yes David this issue effects some users.  I have fixed it in this [commit](https://github.com/aicjofs/zencash-swing-wallet-ui/commit/cba9cb5fd25e86b934652410d739b3f956438f3c)

I have not made a release of it yet, and even compiling it yourself will not fix it unless you delete the zen.conf and run the wallet with the new commit.

The solution for you will be to type in an explorer window %appdata%\zen
From there you will find zen.conf, open it with notepad and add to the end of the file:
addnode=zen.suprnova.cc
addnode=zpool.blockoperations.com
addnode=zen.bitfire.one
addnode=zenmine.pro
addnode=minez.zone

When done your file should look like the one linked in the commit.
